language: python
dist: xenial
python: 3.6
env:
  global:
  - secure: ThnnqMfngB3poftIL98a696loz1p3u7GxV1rkWZBA8HAJaEIsiG91MZDoyyzdRdJllDpva3AcgCd6tbhkQbWX1vgVOx7vUHVlzvlW1WQOAf9JSLSKexVdW1dhBlcXX7EsWyK5lM+m/1cC+CC1xI4iGJ0aMqKe0xe8dOadZ8iZh7r138KpeHmqBeiyOy8zfepDbr5dM+7fgUEGHqbOugEwrDQE2a1tCJoHNXcdxE4pvZJyg3lbm/swGKWbrOzm5sisano/HBEUpQ7B3wtDRmVVKirFu0v3bCcDsCMRucX78MTJUzP+c7t7BzwY6OfU2xJ8Jm2JHhTWT8E6opem4sY2JSxwuO7VWsQoyvvz3BeMY9ND+3VaQfmM1lv8ldL+fMwGtRshtaeCgC/pxYrG9Shf2/T9WiBX5lRvPTj8GeWCTCjUplcKpK9pfroIYKFcIrjuyHqv7eB/WBzUqPm9hEnWq7vU+k7PgrmqHAiQfg2deHgvUk35AMKUhrl1kgF9J6TsQO/DXBrs0/8x8Z1loDUzLx+u8vAIwJ1/qk9FPDN8lgyXulUNufkTUyEezX+PyOanq6vsYRKs/tgeoJSNRJA/54+J9zI1Bo1LT9qcSnfZwtfEG3uAfsQKbqKOCACcNIejQ8LvpxiKm5pvAvPn00L22u1IB80XZQT9ARWTxIUtfY=
before_script:
- git clone https://github.com/uc-cdis/datadictionary && (cd datadictionary && yes | python setup.py install)
script:
- ./run_tests.sh
before_deploy:
  - poetry config pypi-token.pypi $PYPI_API_TOKEN
  - poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -n -vv
  skip_cleanup: true
  on:
    python: 3.6
    repo: uc-cdis/dictionaryutils
    tags: true
after_deploy:
- pip install gen3git
- gen3git release
